apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::267102862828:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-X8RQK11LNOWN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::267102862828:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-05T15:27:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2196"
  uid: e236f3de-f0a3-4dd2-9581-669642817b1f
